import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h1 className="font-heading text-3xl font-bold text-foreground mb-8">Terms of Service</h1>
        <div className="prose-output text-stone-600 space-y-6">
          <p className="text-sm text-stone-400">Last updated: February 4, 2026</p>

          <h2>1. Acceptance of Terms</h2>
          <p>
            By using HireScript (&quot;the Service&quot;), you agree to these Terms of Service. If you do not
            agree, please do not use the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            HireScript is an AI-powered tool that generates job descriptions, interview questions, and
            scoring rubrics. The Service uses artificial intelligence and is intended to assist with—not
            replace—human judgment in hiring processes.
          </p>

          <h2>3. Use of Generated Content</h2>
          <p>
            Content generated by HireScript is provided as a starting point. You are responsible for
            reviewing, editing, and ensuring that all content used in your hiring process complies with
            applicable employment laws and regulations in your jurisdiction.
          </p>

          <h2>4. No Guarantee of Compliance</h2>
          <p>
            While HireScript aims to generate inclusive, bias-free content, we do not guarantee that
            generated content is free from all forms of bias or that it complies with all applicable
            laws. You should always have qualified HR professionals review hiring materials before use.
          </p>

          <h2>5. Free and Paid Plans</h2>
          <p>
            HireScript offers a free tier with limited generations per month. Paid plans with additional
            features may be offered in the future. Pricing and features are subject to change with
            reasonable notice.
          </p>

          <h2>6. Intellectual Property</h2>
          <p>
            You retain ownership of the input you provide. Content generated by the Service is provided
            for your use without restriction. HireScript and its branding, design, and code remain the
            property of Automatik.studio.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            HireScript is provided &quot;as is&quot; without warranty of any kind. We are not liable for any
            damages arising from the use of our Service, including but not limited to hiring decisions
            made based on generated content.
          </p>

          <h2>8. Modifications</h2>
          <p>
            We reserve the right to modify these Terms at any time. Continued use of the Service after
            changes constitutes acceptance of the updated Terms.
          </p>

          <h2>9. Contact</h2>
          <p>
            For questions about these Terms, contact us at{" "}
            <a href="mailto:legal@automatik.studio" className="text-primary-600 hover:text-primary-700">
              legal@automatik.studio
            </a>
            .
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
